defaults: &defaults
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
development:
  <<: *defaults
  bucket: <%=ENV["S3_BUCKET"]%>
test:
  <<: *defaults
  bucket: <%=ENV["S3_BUCKET"]%>
production:
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  bucket: <%=ENV["S3_BUCKET"]%>